name: '🔵 GCP Action'

on:
  workflow_dispatch: {}
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  job_id:
    name: '🆙 GCP'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    if: github.repository == 'digital-clouds/workload'
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.ORG_ID_PROVIDER }}'
          service_account: '${{ secrets.ORG_SERVICE_ACCOUNT }}'
